# Generated by Django 4.1.7 on 2023-04-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='state_of_game',
            field=models.CharField(default='india', max_length=100),
        ),
    ]
